export const collaborationScript=String.raw`
let agentPage=1;
async function agentList(){const d=await api('/api/admin/agent-page?page='+agentPage);el('manageAgentList').replaceChildren();show('agentPageNumber','第 '+agentPage+' 页');el('agentPagePrev').disabled=agentPage<=1;el('agentPageNext').disabled=d.agents.length<50;for(const a of d.agents){const row=document.createElement('div');row.className='item';const text=document.createElement('span');text.textContent=a.name+' · '+a.key_prefix+' · '+a.scopes.join(', ');row.append(text,button('撤销当前空间授权',async()=>{if(!confirm('撤销此 Agent 的当前空间授权？'))return;await api('/api/admin/agents/'+a.id+'/grants/'+sid(),{method:'DELETE'});toast('授权已撤销');}),button('删除密钥',async()=>{if(!confirm('永久删除此密钥？'))return;await api('/api/admin/agents/'+a.id,{method:'DELETE'});await agentList();}));el('manageAgentList').append(row);}}
action('manageAgents',agentList);action('agentPagePrev',()=>{agentPage=Math.max(1,agentPage-1);return agentList();});action('agentPageNext',()=>{agentPage++;return agentList();});
async function jobs(){const d=await api('/api/admin/jobs?space_id='+encodeURIComponent(sid()));el('manageJobs').replaceChildren();for(const j of d.jobs){const row=document.createElement('div');row.className='item';const text=document.createElement('span');text.textContent=j.job_type+' · '+j.status+' · '+JSON.stringify(j.progress);row.append(text);if(j.job_type==='import_v2')row.append(button('明细',async()=>show('manageImportResult',await api('/api/admin/import-queue/'+j.id+'/items'))));if(['pending','processing'].includes(j.status))row.append(button('取消',async()=>{await api('/api/admin/jobs/'+j.id+'/cancel',{method:'POST'});await jobs();}));if(['failed','cancelled'].includes(j.status)&&j.job_type!=='memory_import')row.append(button('重试',async()=>{await api('/api/admin/jobs/'+j.id+'/retry',{method:'POST'});await jobs();}));el('manageJobs').append(row);}}
async function members(){const d=await api('/api/admin/spaces/'+sid()+'/member-page?page='+memberPage);el('manageMembers').replaceChildren();show('memberPage','第 '+memberPage+' 页');el('memberPrev').disabled=memberPage<=1;el('memberNext').disabled=d.members.length<50;for(const m of d.members){const row=document.createElement('div');row.className='item';const text=document.createElement('span');text.textContent=m.display_name+' · '+(m.email||'')+' · '+m.role;const select=document.createElement('select');select.setAttribute('aria-label','成员操作 '+m.display_name);for(const role of ['viewer','contributor','editor','admin','remove','transfer']){const o=document.createElement('option');o.value=role;o.textContent=role;select.append(o);}if(m.role!=='owner')select.value=m.role;row.append(text,select,button('应用',async()=>{if(!confirm('对 '+m.display_name+' 执行 '+select.value+'？'))return;await api('/api/admin/spaces/'+sid()+'/members/'+m.id,{method:'PATCH',body:JSON.stringify({role:select.value})});await refresh();}));el('manageMembers').append(row);}}
action('memberPrev',()=>{memberPage--;return members();});action('memberNext',()=>{memberPage++;return members();});
action('manageAccept',async()=>{await api('/api/admin/invitations/accept',{method:'POST',body:JSON.stringify({token:el('manageInviteToken').value})});el('manageInviteToken').value='';await refresh();});
action('manageInvites',async()=>{const d=await api('/api/admin/spaces/'+sid()+'/invitations');el('manageInvitations').replaceChildren();for(const v of d.invitations){const row=document.createElement('div');row.textContent=v.email+' · '+v.role+' · '+v.expires_at+(v.revoked_at?' 已撤销':v.accepted_at?' 已接受':'');if(!v.accepted_at&&!v.revoked_at)row.append(button('撤销',async()=>{await api('/api/admin/spaces/'+sid()+'/invitations/'+v.id,{method:'DELETE'});row.remove();}));el('manageInvitations').append(row);}});
async function usage(){const d=await api('/api/admin/spaces/'+sid()+'/usage');show('manageUsage',d);el('quotaMemories').value=d.quota.max_memories??'';el('quotaBytes').value=d.quota.max_content_bytes??'';el('quotaCalls').value=d.quota.max_provider_calls_daily??'';}
const numberOrNull=id=>el(id).value===''?null:Number(el(id).value);
action('manageQuota',async()=>{await api('/api/admin/spaces/'+sid()+'/quota',{method:'PUT',body:JSON.stringify({max_memories:numberOrNull('quotaMemories'),max_content_bytes:numberOrNull('quotaBytes'),max_provider_calls_daily:numberOrNull('quotaCalls')})});await usage();});
action('manageMetrics',async()=>show('manageMetricsResult',await api('/api/admin/operations')));
action('manageCleanup',async()=>{if(!confirm('按保留天数永久清理到期审计与导入原文？请先备份。'))return;show('manageMetricsResult',await api('/api/admin/operations/cleanup',{method:'POST',body:JSON.stringify({days:Number(el('manageRetention').value),confirm:'DELETE_EXPIRED_RECORDS'})}));});
`;
