export const managementHtml = `<section id="management"><h1>工作区管理</h1>
<p class="muted">分页与恢复、持久化导入、成员管理及运行状态。内容交换文件不等于数据库备份。</p>
<div class="toolbar"><label>空间 <select id="manageSpace"></select></label><button id="manageRefresh">刷新</button></div>
<div class="box"><h2>记忆浏览与回收站</h2><div class="toolbar">
<input id="manageQuery" placeholder="内容或摘要关键词" aria-label="关键词"><input id="manageTag" placeholder="标签" aria-label="标签">
<select id="manageStatus" aria-label="状态"><option value="active">有效</option><option value="all">全部未删除</option><option value="archived">已归档</option><option value="pending_confirmation">待确认</option><option value="superseded">已替代</option><option value="deleted">回收站</option></select>
<select id="manageType" aria-label="类型"><option value="">全部类型</option>${['fact','preference','event','task','person','project','summary','document','idea','other'].map(x=>`<option>${x}</option>`).join('')}</select>
<select id="manageSort" aria-label="排序"><option value="newest">最新创建</option><option value="oldest">最早创建</option><option value="importance">重要程度</option></select><button id="manageSearch">搜索</button></div>
<div class="toolbar"><button data-batch="archive">归档所选</button><button data-batch="delete">移入回收站</button><button data-batch="restore">恢复所选</button><button data-batch="purge" class="danger">永久删除所选</button></div>
<div id="manageMemories" class="list"></div><div class="toolbar"><button id="managePrev">上一页</button><span id="managePage" role="status"></span><button id="manageNext">下一页</button></div>
<details><summary>版本历史与差异</summary><p>选择一条记忆的「历史」；左右对比仅显示文本，不执行内容。</p><div id="manageVersions"></div><div class="grid"><pre id="manageCurrent" style="white-space:pre-wrap;overflow-wrap:anywhere"></pre><pre id="manageOld" style="white-space:pre-wrap;overflow-wrap:anywhere"></pre></div></details></div>
<div class="box"><h2>可靠导入</h2><input id="manageFile" type="file" accept=".json,.md,.markdown,.txt"><select id="manageFormat"><option value="json">JSON</option><option value="markdown">Markdown</option></select><select id="manageDuplicate"><option value="skip">跳过完全相同内容</option><option value="keep">保留重复</option></select><textarea id="manageImport" aria-label="待导入内容" placeholder="文件或粘贴内容：最多 500 条 / 5 MB"></textarea><button id="managePreview">预检</button> <button id="manageEnqueue">提交后台任务</button><pre id="manageImportResult" style="white-space:pre-wrap"></pre><div id="manageJobs"></div></div>
<div class="box"><h2>成员与邀请</h2><p class="muted">接受邮箱邀请需要本次外部登录提供已验证邮箱。本地资料邮箱不作为证明。</p><input id="manageInviteToken" placeholder="邀请 Token"><button id="manageAccept">接受邀请</button><div id="manageMembers"></div><div class="toolbar"><button id="memberPrev">上一页成员</button><span id="memberPage"></span><button id="memberNext">下一页成员</button></div><button id="manageInvites">查看待处理邀请</button><div id="manageInvitations"></div></div>
<div class="box"><h2>空间用量与配额</h2><pre id="manageUsage" style="white-space:pre-wrap"></pre><p>配额由系统管理员设置；留空为不限额。内容大小只计未删除记忆正文。</p><label>记忆条数 <input id="quotaMemories" type="number" min="1"></label><label>正文总字节 <input id="quotaBytes" type="number" min="1024"></label><label>每日 Provider 调用 <input id="quotaCalls" type="number" min="1"></label><button id="manageQuota">保存配额</button></div>
<div class="box"><h2>Agent 列表</h2><button id="manageAgents">加载我的 Agent</button><div id="manageAgentList"></div><div class="toolbar"><button id="agentPagePrev">上一页 Agent</button><span id="agentPageNumber"></span><button id="agentPageNext">下一页 Agent</button></div></div>
<div id="manageOperations" class="box" style="display:none"><h2>运行状态与保留策略</h2><button id="manageMetrics">刷新系统指标</button><pre id="manageMetricsResult" style="white-space:pre-wrap"></pre><label>保留天数（30–3650）<input id="manageRetention" type="number" value="180" min="30" max="3650"></label><button id="manageCleanup" class="danger">清理到期记录</button><p>每次最多清理 10000 条审计；同时清理过期会话、已终结导入内容和历史调用统计。审计文件 10 MiB 轮转，保留 5 份。</p><h2>离线备份</h2><p>在服务器用 scripts/backup.mjs 创建、校验备份；恢复只允许空数据库。主密钥单独离线保管，Web 不执行恢复。操作步骤见 docs/management-upgrade.md。</p></div>
</section>`;
