import { collaborationScript } from './management-collaboration.js';
export const managementScript=String.raw`(()=>{
'use strict';
const el=id=>document.getElementById(id),selected=new Set();let page=1,memberPage=1,currentId,bootstrap;
const sid=()=>el('manageSpace').value;
const show=(id,value)=>el(id).textContent=typeof value==='string'?value:JSON.stringify(value,null,2);
const action=(id,fn)=>el(id).addEventListener('click',()=>Promise.resolve().then(fn).catch(e=>toast(e.message,true)));
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.addEventListener('click',()=>Promise.resolve().then(fn).catch(e=>toast(e.message,true)));return b;}
async function refresh(){bootstrap=await api('/api/admin/bootstrap');const old=sid();el('manageSpace').replaceChildren();for(const space of bootstrap.spaces){const o=document.createElement('option');o.value=space.id;o.textContent=space.name;el('manageSpace').append(o);}if(bootstrap.spaces.some(x=>x.id===old))el('manageSpace').value=old;el('manageOperations').style.display=bootstrap.me.isSystemAdmin?'block':'none';el('manageQuota').disabled=!bootstrap.me.isSystemAdmin;if(sid())await Promise.all([browse(),members(),usage(),jobs()]);}
async function browse(){if(!sid())return;selected.clear();const q=new URLSearchParams({space_id:sid(),query:el('manageQuery').value,status:el('manageStatus').value,sort:el('manageSort').value,page:String(page),limit:'30'});if(el('manageTag').value)q.set('tag',el('manageTag').value);if(el('manageType').value)q.set('type',el('manageType').value);const d=await api('/api/admin/library?'+q);el('manageMemories').replaceChildren();for(const m of d.memories){const row=document.createElement('div');row.className='item';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.style.minWidth='auto';check.setAttribute('aria-label','选择 '+(m.summary||m.id));check.onchange=()=>check.checked?selected.add(m.id):selected.delete(m.id);label.append(check,document.createTextNode(' '+m.type+' · '+(m.summary||m.content_preview)));row.append(label,button('查看 / 编辑',async()=>{const full=await api('/api/admin/library/'+m.id);if(m.deleted_at){show('manageCurrent',full);return;}el('memorySpace').value=sid();openMemory(full);}),button('历史',()=>history(m.id)));el('manageMemories').append(row);}show('managePage','第 '+page+' 页 / 共 '+d.total+' 条');el('managePrev').disabled=page<=1;el('manageNext').disabled=page*30>=d.total;}
async function history(id,historyPage=1){currentId=id;const [m,h]=await Promise.all([api('/api/admin/library/'+id),api('/api/admin/library/'+id+'/history?page='+historyPage)]);show('manageCurrent',m);el('manageVersions').replaceChildren();for(const v of h.versions){const row=document.createElement('div');row.append(document.createTextNode('v'+v.version+' '+v.reason+' '),button('对比',async()=>{const old=await api('/api/admin/library/'+id+'/versions/'+v.version);const fields=['content','summary','tags','type','status','importance','confidence','sensitivity'];show('manageOld',{version:v.version,changes:fields.filter(k=>JSON.stringify(m[k])!==JSON.stringify(old.snapshot[k])).map(k=>({field:k,current:m[k],previous:old.snapshot[k]}))});}),button('恢复此版本',async()=>{if(!confirm('恢复为此版本并创建新的历史记录？'))return;await api('/api/admin/library/batch',{method:'POST',body:JSON.stringify({space_id:m.space_id,ids:[id],action:'restore',version:v.version})});await history(id);await browse();}));el('manageVersions').append(row);}if(historyPage>1)el('manageVersions').append(button('上一页历史',()=>history(id,historyPage-1)));if(h.versions.length===50)el('manageVersions').append(button('下一页历史',()=>history(id,historyPage+1)));}
for(const b of document.querySelectorAll('[data-batch]'))b.addEventListener('click',async()=>{try{if(!selected.size)throw Error('请先选择记忆');if(!confirm('对 '+selected.size+' 条记录执行 '+b.dataset.batch+'？永久删除不可恢复。'))return;await api('/api/admin/library/batch',{method:'POST',body:JSON.stringify({space_id:sid(),ids:[...selected],action:b.dataset.batch})});await browse();await usage();}catch(e){toast(e.message,true);}});
action('manageRefresh',refresh);action('manageSearch',()=>{page=1;return browse();});action('managePrev',()=>{page--;return browse();});action('manageNext',()=>{page++;return browse();});el('manageSpace').addEventListener('change',()=>{page=1;memberPage=1;refresh().catch(e=>toast(e.message,true));});
const input=()=>({space_id:sid(),format:el('manageFormat').value,content:el('manageImport').value,duplicates:el('manageDuplicate').value});
el('manageFile').addEventListener('change',async()=>{try{const f=el('manageFile').files[0];if(!f)return;if(f.size>5000000)throw Error('文件超过 5 MB');el('manageImport').value=await f.text();el('manageFormat').value=f.name.endsWith('.json')?'json':'markdown';}catch(e){toast(e.message,true);}});
action('managePreview',async()=>show('manageImportResult',await api('/api/admin/import-queue/preview',{method:'POST',body:JSON.stringify(input())})));
action('manageEnqueue',async()=>{el('manageEnqueue').disabled=true;try{show('manageImportResult',await api('/api/admin/import-queue',{method:'POST',body:JSON.stringify(input())}));await jobs();}finally{el('manageEnqueue').disabled=false;}});
`+collaborationScript+String.raw`
document.querySelector('[data-view="management"]').addEventListener('click',()=>refresh().catch(e=>toast(e.message,true)));
let polling=false;setInterval(async()=>{if(polling||!el('management').classList.contains('active')||!sid())return;polling=true;try{await jobs();}catch{}finally{polling=false;}},5000);
})();`;
